//! Build script for steam-protobuf-rs.
//!
//! When the `codegen` feature is enabled (CI/development), this script runs
//! prost-build to compile all `.proto` files under `protos/` into Rust types
//! and writes them to `src/generated/`.
//!
//! When `codegen` is disabled (the default for end users), this script is a
//! no-op — the pre-committed generated code in `src/generated/` is used directly.

fn main() {
    #[cfg(feature = "codegen")]
    codegen::generate();
}

#[cfg(feature = "codegen")]
mod codegen {
    use std::fs;
    use std::path::{Path, PathBuf};

    pub fn generate() {
        let proto_dir = Path::new("protos");
        let out_dir = Path::new("src/generated");

        // Collect all .proto files (excluding google/ well-known types — prost
        // handles those internally, but we still need them on the include path).
        let proto_files: Vec<PathBuf> = collect_proto_files(proto_dir);

        if proto_files.is_empty() {
            panic!("No .proto files found in {}", proto_dir.display());
        }

        // Ensure output directory exists.
        fs::create_dir_all(out_dir).expect("Failed to create src/generated/");

        // Configure prost-build.
        let mut config = prost_build::Config::new();
        config.out_dir(out_dir);

        // Compile all protos with `protos/` as the include root.
        config
            .compile_protos(&proto_files, &[proto_dir.to_path_buf()])
            .expect("prost-build failed to compile .proto files");

        // Generate mod.rs from the files prost-build produced.
        generate_mod_rs(out_dir);
    }

    /// Recursively collects all `.proto` files under `dir`, excluding the
    /// `google/` subdirectory (those are well-known types handled by prost).
    fn collect_proto_files(dir: &Path) -> Vec<PathBuf> {
        let mut files = Vec::new();

        for entry in fs::read_dir(dir).expect("Failed to read protos/ directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();

            if path.is_dir() {
                // Skip google/ — prost-build resolves well-known types internally.
                if path.file_name().is_some_and(|n| n == "google") {
                    continue;
                }
                files.extend(collect_proto_files(&path));
            } else if path.extension().is_some_and(|ext| ext == "proto") {
                files.push(path);
            }
        }

        files
    }

    /// Scans `out_dir` for generated `.rs` files and writes a `mod.rs` that
    /// re-exports every module.
    fn generate_mod_rs(out_dir: &Path) {
        let mut modules: Vec<String> = Vec::new();

        for entry in fs::read_dir(out_dir).expect("Failed to read generated/ directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();

            if path.extension().is_some_and(|ext| ext == "rs") {
                let stem = path
                    .file_stem()
                    .expect("No file stem")
                    .to_str()
                    .expect("Non-UTF-8 filename");

                // Skip mod.rs itself.
                if stem == "mod" {
                    continue;
                }

                modules.push(stem.to_string());
            }
        }

        modules.sort();

        let mut content = String::from("// @generated by build.rs — do not edit.\n\n");

        // The default prost package (no package declaration) produces `_.rs`.
        // We re-export it as `pub mod _` which is invalid Rust, so we handle
        // it specially: include! it at the crate root instead.
        let mut has_default = false;

        for module in &modules {
            if module == "_" {
                has_default = true;
                continue;
            }
            content.push_str(&format!("#[allow(clippy::all)]\npub mod {module};\n"));
        }

        if has_default {
            // Include the default-package file directly so its types live at
            // the crate root (no nested module needed).
            // Note: #[allow] on include!() is ignored by rustc — the allow is
            // set on `mod generated` in lib.rs instead.
            content.push_str(
                "\n// All Steam proto files have no `package` declaration, so prost-build puts\n\
                 // every type into the default package file (`_.rs`).  We include it here so\n\
                 // all types are accessible directly from the crate root.\n\
                 include!(\"_.rs\");\n",
            );
        }

        fs::write(out_dir.join("mod.rs"), content).expect("Failed to write src/generated/mod.rs");
    }
}
